//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::albums::Entity as Albums;
pub use super::artists::Entity as Artists;
pub use super::listening_events::Entity as ListeningEvents;
